2017-11-26 01:33:08,569:WARNING:Not Found: /favicon.ico
2017-11-26 01:34:58,576:WARNING:Not Found: /login/
2017-11-26 01:35:43,849:ERROR:Internal Server Error: /
Traceback (most recent call last):
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/edward/project/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/edward/project/lib/python3.6/site-packages/django/template/response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: welcome/index.html
2017-11-26 01:39:11,789:WARNING:Not Found: /account/login/
2017-11-26 01:39:29,525:WARNING:Not Found: /account/login/
2017-11-27 15:33:11,919:WARNING:Not Found: /favicon.ico
2017-11-27 15:35:31,459:WARNING:Not Found: /account/register/
2017-11-27 15:37:15,435:WARNING:Not Found: /account/register/
2017-11-27 15:37:16,238:WARNING:Not Found: /account/register/
2017-11-27 15:37:16,845:WARNING:Not Found: /account/register/
2017-11-27 15:37:17,575:WARNING:Not Found: /account/register/
2017-11-27 15:37:24,593:WARNING:Not Found: /account/register/
2017-11-27 15:39:10,570:ERROR:Internal Server Error: /account/auth
Traceback (most recent call last):
  File "/home/edward/project/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edward/project/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/edward/comp3335/comp3335/account/views.py", line 41, in auth
    username = msg_encrypt(request.POST["email"])
  File "/home/edward/project/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'email'"
2017-11-27 17:52:55,248:ERROR:Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edward/comp3335/comp3335/dashboard/views.py", line 18, in index
    courses.name = msg_decrypt(course.name)
NameError: name 'course' is not defined
2017-11-27 17:53:11,879:INFO:request course list for dashboard
2017-11-27 17:53:54,678:INFO:request course list for dashboard
2017-11-27 17:53:54,679:ERROR:Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edward/comp3335/comp3335/dashboard/views.py", line 21, in index
    return render(request, 'dashboard/board/index.html', {'courses': test_courses})
  File "/home/edward/project/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/defaulttags.py", line 983, in do_if
    nodelist = parser.parse(('endif',))
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/defaulttags.py", line 827, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 486, in parse
    raise self.error(token, e)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 484, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 700, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' +':'+ course.name' from 'course.code +':'+ course.name'
2017-11-27 17:54:14,870:INFO:request course list for dashboard
2017-11-27 17:54:14,871:ERROR:Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edward/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edward/comp3335/comp3335/dashboard/views.py", line 21, in index
    return render(request, 'dashboard/board/index.html', {'courses': test_courses})
  File "/home/edward/project/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/defaulttags.py", line 983, in do_if
    nodelist = parser.parse(('endif',))
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/defaulttags.py", line 827, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 486, in parse
    raise self.error(token, e)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 484, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/edward/project/lib/python3.6/site-packages/django/template/base.py", line 700, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' + course.name' from 'course.code + course.name'
2017-11-27 17:55:16,329:INFO:request course list for dashboard
2017-11-27 17:55:25,548:INFO:request course list for dashboard
2017-11-27 17:55:30,002:INFO:request course detail success: course code = AMA2882
2017-11-27 17:55:34,191:INFO:request course detail success: course code = COMP3335
2017-11-27 17:55:45,967:INFO:request course detail success: course code = COMP3335
2017-11-27 17:56:47,297:INFO:request course detail success: course code = COMP3335
2017-11-27 17:56:51,927:INFO:request course detail success: course code = COMP3335
2017-11-27 17:57:00,561:INFO:request course detail success: course code = COMP3335
2017-11-27 17:57:08,916:INFO:request course detail success: course code = COMP3335
2017-11-27 17:58:00,719:INFO:request course detail success: course code = COMP3335
2017-11-27 17:59:42,797:INFO:request course detail success: course code = COMP3335
2017-11-27 17:59:49,823:INFO:request course detail success: course code = COMP4431
2017-11-27 17:59:51,954:INFO:request course detail success: course code = AMA2882
2017-11-27 17:59:55,458:INFO:request course detail success: course code = AMA1130
2017-11-27 17:59:57,521:INFO:request course detail success: course code = COMP2432
